### PR TITLE
chore(map-dependencies): Update map dependencies (#269-update-mapbox-gl)

### PR DESCRIPTION
**Pull request by vogelino**
**Udpated the following dependencies:**
- react-map-gl@latest
- deck.gl@latest
- @types/react-map-gl@latest
- @danmarshall/deckgl-typings@latest

For now, one visible change is the difference between yellow tones while very zoomed out.
|**Before**|**After**|
|-|-|
|image|image|

I feel like this is related to the yellow border that surrounds each dot on the map.
I will investigate.

### CODE REVIEW

**Comment by vogelino** [comment]
It does indeed fix the problem of dots not being displayed on apple silicon M1 MacBooks! 🥳  
FYI: @Esshahn

**Comment by Esshahn** [comment]
Bildschirmfoto 2021-02-15 um 18 00 26
I see the trees but not the city map

**Comment by vogelino** [comment]
> I see the trees but not the city map

This is normal this is just a preview thing. You won't have this problem when it's merged.

**Review by ff6347 — APPROVED** [review]
Fixed the conflicts. LGTM

**Pull request merged**
