### PR TITLE
feat: move and style language button

### PR DESCRIPTION
**Pull request by aeschi**
- moved language button to fixed top right position
- added styling according to new design on figma
- the language button is currently rendered double in OverlayTop (where it already was) AND in the main App file. Otherwise clicking the language button outside the splash screen would always close the splash screen.

https://app.asana.com/0/1204152181784036/1206565413148089/f

### CODE REVIEW

**Comment by Jaszkowic** [comment]
@aeschi is this WIP or ready to review?

**Comment by aeschi** [comment]
@Jaszkowic depends if we want to have the toggle already in staging, but I think it would be helpful. The double rendering of the toggle is not so nice - maybe we can find a better solution for that, so a review would be great.

**Comment by Jaszkowic** [comment]
@aeschi I fixed the double rendering in https://github.com/technologiestiftung/giessdenkiez-de/pull/696/commits/1f8d6023595ad4c9e5a62896bc72d063423a51cb by setting `z-index` to be higher than `z-index` of the overlay

**Comment by Jaszkowic** [comment]
@HenrietteN I think we should merge this soon

**Review by Jaszkowic — APPROVED** [review]
LGTM

**Pull request merged**
