### PR TITLE
fix/signup notification

### PR DESCRIPTION
**Pull request by ff6347**
- fix(types): Move types closer to component
- fix(types): Import moved types
- fix(validation): Remove duplicate information
- feat(notification): Add notification under input
- chore: Cleanup
- fix(notification): Remove duplicate
- fix(spelling): Dich like in PR #674

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1206271447147981

### CODE REVIEW

**Comment by Jaszkowic** [comment]
@ff6347   Not sure if I test this wrong, but I get "Bitte überprüfe Deinen Nutzernamen" in the UI although the username (`jonasjaszkowic1234`) complies to the patterns. in the console I checked `usernamePatterns` to be:

> {allowedLength: true, minLength: true, maxLength: true, allowedCharacters: true, taken: false}

which should allow signup, right?

i think this line might be wrong (?):

```
if (Object.values(usernamePatterns).every(Boolean) === false)
```

it i understand correctly, this checks if not all fields are true and if not all fields are true, it shows the error. but `taken` should be false to allow signup.

**Review by aeschi — CHANGES_REQUESTED** [review]
task 1 and 2 from asana are working. When trying out 3. "Restrict duplicates for user names for already existing users" I was forwarded to the error page.

verification of username and password characteristics is also working.

https://app.asana.com/0/0/1206271447147981

**Comment by raphael-arce** [comment]
@aeschi You're right, I forgot that you could change your username there 😄 I just updated the username change modal. Would you mind having another look?

**Review by aeschi — APPROVED** [review]
LGTM 👍

**Pull request merged**
