### PR TITLE
Fix/password recovery form not shown

### PR DESCRIPTION
**Pull request by raphael-arce**

### CODE REVIEW

**Comment by ff6347** [comment]
@raphael-arce Yes I will. Does it work in the deploy preview?

**Comment by raphael-arce** [comment]
@ff6347 No, I'm getting redirected to the staging url, and not the current branch preview url

**Comment by ff6347** [comment]
Nope. I get directly to `/profile` and don't get the recovery form :/

**Comment by ff6347** [comment]
ah okay. I need to change the env var?

**Comment by ff6347** [comment]
Now I land on the password-reset but I don't get the form. It is stuck in loading state.

image

**Comment by ff6347** [comment]
The recovery does not fire when I come in over that url

**Review by ff6347 — APPROVED** [review]
LGTM. We need to test this in the staging env

**Pull request merged**
