### PR TITLE
feat: exchange logos and adapt order

### PR DESCRIPTION
**Pull request by aeschi**
task details: https://app.asana.com/0/1204152181784036/1206609812447162/f

### CODE REVIEW

**Comment by ff6347** [comment]
@aeschi Tests are failing?

**Comment by ff6347** [comment]
The test should not link to an external resource

**Comment by aeschi** [comment]
@ff6347  I forgot to change the test file, thanks!

**Review by ff6347 — APPROVED** [review]
LGTM

**Pull request merged**
