### PR TITLE
fix: remove deckgl, remove rain layer

### PR DESCRIPTION
**Pull request by Jaszkowic**
- Remove Deck.gl completely
- Remove rain layer
- Let Mapbox handle the viewport itself, use `easeTo` instead of manipulating the viewport manually
- Customize zoom rate for smoother zooming

### CODE REVIEW

**Comment by Jaszkowic** [comment]
Closing for now, we might want to do this at a later point when doing the UI rework.

**Review by aeschi — COMMENTED** [review]
- legend.precipitationAreas can now be deleted from the translation file I think?
- the zoom speed seems a bit to fast for me when scrolling
- otherwise LGTM :)

**Comment by Jaszkowic** [comment]
Don't merge yet, waiting for PO approval @HenrietteN

**Review by ff6347 — APPROVED** [review]
Pretty snappy. Me like!

**Pull request merged**
