### PR TITLE
fix: jumpy zoom

### PR DESCRIPTION
**Pull request by Jaszkowic**
Map zoom was controlled by DeckGL and Map component, which led to weird jumpy behavior. It's now controlled by DeckGL exclusively. Furthermore, I removed some unnecessary minzoom, maxzoom settings.

### CODE REVIEW

**Comment by ff6347** [comment]
How can I test this locally? I think our CORS settings on the staging api are blocking to zoom to a clicked tree

**Comment by Jaszkowic** [comment]
@ff6347 I have the API running locally to test

**Comment by ff6347** [comment]
@Jaszkowic
- Works for zooming to trees 👍🏾 
- For me it does not zoom to my location

**Comment by Jaszkowic** [comment]
@ff6347 

Fixed, should zoom to tree an click and to geolocate position on locate

**Review by ff6347 — APPROVED** [review]
LGTM

**Pull request merged**
