### PR TITLE
refactor: simplify the stats page and its components

### PR DESCRIPTION
**Pull request by raphael-arce**
The goal is to simplify / make the components more readable. @aeschi @Jaszkowic let me know what you think :)

(I also added a missing translation for "Andere" in the donut chart and fixed a visual bug when you would hover the legend in the "Gießverhalten" chart)

### CODE REVIEW

**Comment by Jaszkowic** [comment]
@raphael-arce thanks for your effort :) Looks good! But for me, the preview link is not working - it does not render the charts. Do you know whats up? The `gdk_stats` request returns with valid data.
image

**Comment by raphael-arce** [comment]
@Jaszkowic hmm i don't know whats wrong. Locally it works. Will look into it 👍

**Comment by raphael-arce** [comment]
@Jaszkowic found the issue and fixed it 👍 the resize function was called before the `stats-card-container` element was added to the dom, then no width would be set on page load.

**Review by Jaszkowic — APPROVED** [review]
Nice work!

**Pull request merged**
