### PR TITLE
Staging to Master

### PR DESCRIPTION
**Pull request by vogelino**
This PR merges the PR #460 into Master and thereby releases the OSM Editor Link in the Tooltips.

### CODE REVIEW

**Comment by julizet** [comment]
Thanks for this really rigorous and even so quick review an PR @vogelino @dnsos @ff6347!

I've tested the deploy preview and found three things that could be improved – UX- and design-wise:
1. it would be nice if one could close the sticky pump overlay. Once clicked it's there forever.
2. when I clicked on a pump I see the sticky overlay. If I then change to the trees or rainfall layer, I can still see my stick pump overlay. Would be nice if it deisappears when the user changes the layer.
3. the text-link to the editor should be aligned to the left

Please see the two screenshots attached and let me know what you think.

Tested on Catalina 10.15.4 with Firefox 99.0.1 
462_changeLayer
462_stickyOverlay

**Comment by ff6347** [comment]
Good catch with changing the view type. The overlay disappears when moving the map but having a close button would be more explicit.

About the alignment: I actually like it on the right hand side. It's like you enter top left and leave bottom right.

**Comment by vogelino** [comment]
Hi @julizet and thx for your feedback! I agree with @ff6347 that the right alignment is well suited as last element on the tooltip. To be honest, this wasn't the reason why I did it though, much more it was because it was way easier to implement this way. Making it left aligned would require additional work. 

I am now also closing the tooltip every time the mouse clicks outside of the tooltip. This solves every problems that you mentioned above. It makes the X obsolete I think. Here is the PR: #466

**Comment by vogelino** [comment]
@torbans the preview URL is this one: https://deploy-preview-462--giessdenkiez.netlify.app/

**Comment by julizet** [comment]
> Hi @julizet and thx for your feedback! I agree with @ff6347 that the right alignment is well suited as last element on the tooltip. To be honest, this wasn't the reason why I did it though, much more it was because it was way easier to implement this way. Making it left aligned would require additional work.
> 
> I am now also closing the tooltip every time the mouse clicks outside of the tooltip. This solves every problem mentioned above. It makes the X obsolete I think. Here is the PR: #466

I agree with that -> clicking outside of the tooltip is a lightweight UX-solution. Let's skip this left-alignment in order to save dev capacities. If [@tordans](https://github.com/tordans) doesn't has anx further comments / feedback we are good to merge into main, IMHO

**Comment by vogelino** [comment]
Perfect @julizet. Thx for your feedback! I will merge it now.

**Comment by tordans** [comment]
Looks great! Thanks! Will Twitter via `@osmberlin` once it is live. Will try adding clustering to the map later to improve the editing experience.

**Pull request merged**
