### PR TITLE
feat: hide splash screen for a week after closing it

### PR DESCRIPTION
**Pull request by raphael-arce**
This PR hides the splash screen for a week after closing it

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1207010784875414

### CODE REVIEW

**Review by Jaszkowic — CHANGES_REQUESTED** [review]
I think we could use Zustand feature of persisting to localStorage instead of manually writing it to / reading it from localStorage...  https://docs.pmnd.rs/zustand/integrations/persisting-store-data or are there reasons against it?

**Comment by raphael-arce** [comment]
@Jaszkowic no reasons against it, I forgot that zustand had this feature. you are absolutely right! will change 👍

**Comment by raphael-arce** [comment]
@Jaszkowic would you be so kind to have another look? 🙏

**Review by Jaszkowic — APPROVED** [review]
Ship it 🚀

**Pull request merged**
