### PR TITLE
Uplift requests 

### PR DESCRIPTION
**Pull request by ff6347**
This is moves the API requests into the Card component and makes
the button a pure UI component with no side effects.

### CODE REVIEW

**Comment by vogelino** [comment]
Looking at this code getting 🧼🧽🧹 makes me horny 🤤

**Comment by vogelino** [comment]
Great improvements here! Thanks a lot! Merging this branch is going to be a pain though. We both did consequent changes in the same files. Maybe a pair programming session is necessary. 🤓🤓

**Comment by ff6347** [comment]
> Great improvements here! Thanks a lot! Merging this branch is going to be a pain though. We both did consequent changes in the same files. Maybe a pair programming session is necessary. 🤓🤓

Just push your changes and I will try to sort out the confilcts

**Comment by vogelino** [comment]
> Just push your changes and I will try to sort out the confilcts

You wish it was that easy :P My changes are pushed but there is still work to do here and there and bugs might be remaining.

**Pull request merged**
