### PR TITLE
chore(templates): Adds email templates to vcs

### PR DESCRIPTION
**Pull request by ff6347**
This PR adds our email templates to the VCS so other cities can build on it.

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1204648985914352

### CODE REVIEW

**Comment by ff6347** [comment]
@JensWinter These are the current templates we use. Magic link and invite user are not defined and just use the default, since we are not using them currently.

**Comment by JensWinter** [comment]
Thank you so much! Unfortunately there is no way to automate this or configure the templates via vercel.json or anything

**Comment by ff6347** [comment]
@JensWinter No there is nothing official. When self hosted there is some gotrue env variable which can load templates for the emails from an url, but we will have to add these manually to the backend. Still better to have them in the VCS then only in the supbase backend.

**Comment by ff6347** [comment]
> Should we mention somewhere that supabase automatically removes comments in html, which results in a difficult task to optimize the e-mail template for some e-mail clients? Otherwise LGTM

Yes. I did not know that. This is something for the `wiki > backend > supabase`

**Pull request merged**
