### PR TITLE
chore: update dwd to 2.6.0

### PR DESCRIPTION
**Pull request by Jaszkowic**

### CODE REVIEW

**Comment by Jaszkowic** [comment]
@aeschi this fixed the GdK Stats bug where the latest weather data was not available

**Review by aeschi — APPROVED** [review]
LGTM! 👍

**Comment by aeschi** [comment]
@Jaszkowic in the preview link I can't see any data though..

**Comment by Jaszkowic** [comment]
@aeschi yes, the action needs to be triggered first

**Pull request merged**
