### PR TITLE
chore(Housekeeping): Remove axios dependency and dead code

### PR DESCRIPTION
**Pull request by ff6347**
This removes axios since it was fully replaced by fetch. The only
trace we had left in there was in the function `fetchAPI` which was called
in a dead component called `SidebarAdopted`. This was not used at all.
Also removes `IconRemove` which also was used by `SidebarAdopted` and
noone else.

There where also another dead route called `selected`.

Also removes it from storybook and updates test snapshots.

close #231

### CODE REVIEW

**Review by vogelino — APPROVED** [review]

**Comment by vogelino** [comment]
Cool! Weird Sidebar though. Could you find out when it was dropped in favour of the info in the profile sidebar?

**Comment by ff6347** [comment]
@julizet @dnsos Can you also please take a look. There as a route called `selected` in the router. Which never gets called, right?
Also there was the component `adopted` which should have opened a own sidebar section for the adopted trees I guess. I think that was also never used, right?

**Review by dnsos — COMMENTED** [review]
I'm not exactly aware of the routes used or not used, but what I can say for now is that the sidebar is not behaving correctly. Selecting a tree opens the "Suche & Filter" view instead of the tree details.

**Comment by ff6347** [comment]
> I'm not exactly aware of the routes used or not used, but what I can say for now is that the sidebar is not behaving correctly. Selecting a tree opens the "Suche & Filter" view instead of the tree details.

But it does search for tree details...?

**Comment by ff6347** [comment]
@dnsos The same thing happens in production. There is no "tree view" it always says "Suche & Filter" on top of the details of the tree

**Comment by dnsos** [comment]
@ff6347 sorry, my "Suche & Filter" statement was unclear. It's the **tree details** that are not showing up. You can't reproduce? Maybe this is a local issue of mine then...

https://user-images.githubusercontent.com/15640196/106632351-f1fae080-657d-11eb-8c89-00e3f43471b5.mp4

**Comment by ff6347** [comment]
Are you using the real API or the dev API. If in dev you need to go to my street corner. There are only 10000 trees in there.

**Comment by dnsos** [comment]
Ahh, of course! I had forgotten about that 🤦  Nevermind my comment, it works.

**Pull request merged**
