### PR TITLE
docs improvements

### PR DESCRIPTION
**Pull request by danielsippel**

### CODE REVIEW

**Comment by ff6347** [comment]
@danielsippel Thanks for the pr. we did some changes over the last two weeks and we might need to change the docs as well. @vogelino  did you change the API_URL ENV variable?

**Comment by vogelino** [comment]
> @danielsippel Thanks for the pr. we did some changes over the last two weeks and we might need to change the docs as well. @vogelino did you change the API_URL ENV variable?

Hi @danielsippel! I think we are definitively missing an `.env.sample` file. Thank you for your contribution.

Some the variable like `URL_ENV` is deprecated. My `.env.sample` file would look like this (I would want to avoid using real api URLs here, except for the prod API endpoint), but I would prefer fake values that resemble closely the real values (it makes it easier to find the values within the auth0 configuration page):
```bash
# ATTENTION: no trailing slash at the end of URL!!
API_KEY=pk.qe2891fu38e189p3uf1p98u3fp1932fp912839fu12p839fup1239uf1p238fu12p398fp19fj328f0.2D_83924dj1-JLM89N_8da
AUTH0_DOMAIN=myauthzeropath.eu.auth0.com
AUTH0_CLIENT_ID=IUONiojufw8273r9POMJIUjuofuwpPwe
AUTH0_AUDIENCE=https://my-tree-api-url.io
USER_DATA_API_URL=https://my-user-management-api.io
API_ENDPOINT_DEV=https://localhost:8000/my-local-postgres-api
API_ENDPOINT_PROD=https://giessdenkiez-de-postgres-api.vercel.app
```
I think most comments are unnecessary and would favour explicit variable names. I like that you added the warning about trailing slashes though!

@ff6347 What do you think? PS: No I didn't change the `API_URL` environment variable. I fact I don't have one called `API_URL`.

**Comment by vogelino** [comment]
Also, I would want to change the name of the variable `API_KEY` to `MAPBOX_API_KEY`. Anyone against that?

**Comment by vogelino** [comment]
One more thing @ff6347. Can you explain the difference between the `AUTH0_AUDIENCE` and the `API_ENDPOINT`?

**Comment by ff6347** [comment]
> One more thing @ff6347. Can you explain the difference between the `AUTH0_AUDIENCE` and the `API_ENDPOINT`?

AUTH0_AUDIENCE is just a name for the application in the auth0com tenant it is no real URL that gets called

**Comment by vogelino** [comment]
> > One more thing @ff6347. Can you explain the difference between the `AUTH0_AUDIENCE` and the `API_ENDPOINT`?
> 
> AUTH0_AUDIENCE is just a name for the application in the auth0com tenant it is no real URL that gets called

Ok thx @ff6347. So can we remove it? If not how can we make clear what it is in your opinion?

**Comment by vogelino** [comment]
I created a new PR #303 that fixes this PR #302 because I could not checkout the branch `danielsippel:docs/improvements`

**Comment by ff6347** [comment]
> Ok thx @ff6347. So can we remove it? If not how can we make clear what it is in your opinion?

I'm pretty sure it is needed for auth0. Please dir remove it

**Comment by ff6347** [comment]
I'll will review what this is for our where it comes from

**Pull request closed without merging**
