### PR TITLE
feat: use fixed size modal

### PR DESCRIPTION
**Pull request by raphael-arce**

### CODE REVIEW

**Comment by ff6347** [comment]
Are you going to alter all the modals? 

we have a modals for:

- [x] Password edit
- [ ] Account Edit (Email/Username)
- [ ] Watering Modal

**Review by dnsos — CHANGES_REQUESTED** [review]
Nice, this prevents the jumping indeed!

I would like to discuss the implementation of the `NotificationPlaceholder`, see my comment below.

**Review by dnsos — APPROVED** [review]
I like it! Thanks for the changes!

**Comment by dnsos** [comment]
> therefore only one placeholder/spacer would not work in that case.

Yes, I can see the issue. I'm open to discussing other approaches, but also happy to merge this for now and do it afterwards.

**Pull request merged**
